import type { SlideData } from './types';
import MentalHealthChart from './components/charts/MentalHealthChart';
import GlobalUsageChart from './components/charts/GlobalUsageChart';
import CreatorEconomyChart from './components/charts/CreatorEconomyChart';

export const PRESENTATION_DATA: SlideData[] = [
  // --- Presenter 1: Overview of Social Media (Slides 1-10) ---
  { // 1
    title: 'The Evolution of Social Media',
    subtitle: 'From Niche Communities to a Global Phenomenon',
    points: [
      'An in-depth look at the past, present, and future of social connection.',
      'Presented by your hosts for this journey through the digital landscape.',
    ],
    image: 'https://picsum.photos/id/1015/1200/800',
    layout: 'text-only',
    presenter: 1,
  },
  { // 2
    title: 'Presentation Roadmap',
    subtitle: 'Our Journey Through the Digital Landscape',
    points: [
      'Part 1: The Overview & History (Presenter 1)',
      'Part 2: The Impact on Society (Presenter 2)',
      'Part 3: The Future Ahead (Presenter 3)',
    ],
    image: 'https://picsum.photos/id/1040/1200/800',
    layout: 'text-left',
    presenter: 1,
  },
  { // 3
    title: 'What is Social Media?',
    subtitle: 'Defining the Core Concepts',
    points: [
      'Digital platforms facilitating the creation and sharing of information, ideas, and content.',
      'Built on the foundation of user-generated content and virtual communities.',
      'Characterized by profiles, connections (friends/followers), and interactive feeds.',
    ],
    image: 'https://picsum.photos/id/237/1200/800',
    layout: 'text-right',
    presenter: 1,
  },
  { // 4
    title: 'The Precursors: Before Social Media',
    subtitle: 'The Dawn of Online Communities',
    points: [
      'Bulletin Board Systems (BBS) and Usenet created the first digital forums.',
      'IRC (Internet Relay Chat) enabled real-time text-based communication.',
      'These platforms were decentralized and focused on specific topics, not individual profiles.',
    ],
    image: 'https://picsum.photos/id/535/1200/800',
    layout: 'text-left',
    presenter: 1,
  },
  { // 5
    title: 'The First Wave: Early Networks',
    subtitle: 'The Birth of the Social Profile',
    points: [
      'SixDegrees.com (1997) was the first to combine profiles with friend lists.',
      'Friendster (2002) popularized the concept of a "circle of friends".',
      'MySpace (2003) dominated by allowing deep profile customization with music and HTML.',
    ],
    image: 'https://picsum.photos/id/1078/1200/800',
    layout: 'text-right',
    presenter: 1,
  },
  { // 6
    title: 'Rise of the Giants: Facebook & YouTube',
    subtitle: 'Connecting the World and Sharing its Stories',
    points: [
      'Facebook (2004) shifted focus to real identities and the "News Feed".',
      'Its platform approach integrated games, events, and third-party apps.',
      'YouTube (2005) democratized video, creating a new medium for entertainment and information.',
    ],
    image: 'https://picsum.photos/id/1025/1200/800',
    layout: 'text-left',
    presenter: 1,
  },
  { // 7
    title: 'The Mobile & Visual Revolution',
    subtitle: 'Twitter, Instagram, and the Power of Now',
    points: [
      'Twitter (2006) introduced microblogging and the concept of the real-time "hashtag".',
      'Instagram (2010) embraced a mobile-first, visual-centric experience.',
      'This era marked the shift to on-the-go consumption and ephemeral content (Stories).',
    ],
    image: 'https://picsum.photos/id/1062/1200/800',
    layout: 'text-right',
    presenter: 1,
  },
  { // 8
    title: 'The Global Town Square',
    subtitle: 'Billions Connected and Counting',
    points: [
      'Social media has transcended borders, becoming a primary source of information and connection.',
      'Over 5 billion active users, representing a majority of the world\'s population.',
      'Emerging markets in Asia and Africa are driving future growth.',
    ],
    image: 'https://picsum.photos/id/1043/1200/800',
    chart: GlobalUsageChart,
    layout: 'text-left',
    presenter: 1,
  },
  { // 9
    title: 'The Modern Social Ecosystem',
    subtitle: 'A Platform for Every Purpose',
    points: [
      'Social Networks (Facebook, LinkedIn)',
      'Media Sharing (YouTube, TikTok, Instagram, Pinterest)',
      'Discussion Forums (Reddit, Quora)',
      'Messaging Apps (WhatsApp, Messenger) have become social hubs.',
    ],
    image: 'https://picsum.photos/id/319/1200/800',
    layout: 'text-right',
    presenter: 1,
  },
  { // 10
    title: 'Key Terminology',
    subtitle: 'The Language of Social Media',
    points: [
      'Algorithm: The system that decides what content you see.',
      'Engagement: Likes, comments, shares, and other interactions.',
      'Virality: The rapid, widespread sharing of a piece of content.',
      'Influencer: A user with a dedicated following who can affect purchase decisions.',
    ],
    image: 'https://picsum.photos/id/24/1200/800',
    layout: 'text-left',
    presenter: 1,
  },
  // --- Presenter 2: The Impact of Social Media (Slides 11-20) ---
  { // 11
    title: 'Reshaping Communication',
    subtitle: 'How We Connect, Share, and Learn',
    points: [
      'Democratized information, giving a voice to individuals and movements.',
      'Citizen journalism provides real-time, on-the-ground reporting.',
      'Changed social etiquette and the nature of personal relationships.',
    ],
    image: 'https://picsum.photos/id/367/1200/800',
    layout: 'text-right',
    presenter: 2,
  },
  { // 12
    title: 'A New Era for Business',
    subtitle: 'From Marketing to Social Commerce',
    points: [
      'Direct-to-consumer marketing allows brands to build relationships.',
      'Hyper-targeted advertising based on user data and behavior.',
      'Social proof (reviews, testimonials) has become a key driver of sales.',
    ],
    image: 'https://picsum.photos/id/1074/1200/800',
    layout: 'text-left',
    presenter: 2,
  },
  { // 13
    title: 'The Creator Economy',
    subtitle: 'Turning Passion into a Profession',
    points: [
      'Enabled individuals to monetize their content and build personal brands.',
      'Projected to reach nearly half a trillion dollars by 2027.',
      'Platforms provide tools for subscriptions, tips, and brand partnerships.',
    ],
    image: 'https://picsum.photos/id/1079/1200/800',
    chart: CreatorEconomyChart,
    layout: 'text-right',
    presenter: 2,
  },
  { // 14
    title: 'A Force for Social Good',
    subtitle: 'Mobilizing Communities for Change',
    points: [
      'Powerful tool for activism and social movements (e.g., #BlackLivesMatter, Arab Spring).',
      'Facilitates crowdfunding for personal emergencies and charitable causes.',
      'Creates global support networks for individuals with shared experiences.',
    ],
    image: 'https://picsum.photos/id/1084/1200/800',
    layout: 'text-left',
    presenter: 2,
  },
  { // 15
    title: 'The Mental Health Dilemma',
    subtitle: 'The Cost of Constant Connection',
    points: [
      'Correlation between high social media use and increased rates of anxiety and depression.',
      'Social comparison, cyberbullying, and FOMO (Fear Of Missing Out) are major concerns.',
      'Many users report a negative impact on their self-esteem and body image.',
    ],
    image: 'https://picsum.photos/id/1056/1200/800',
    chart: MentalHealthChart,
    layout: 'text-right',
    presenter: 2,
  },
  { // 16
    title: 'The Misinformation Challenge',
    subtitle: 'When Virality Meets Inaccuracy',
    points: [
      'False narratives can spread faster and wider than factual information.',
      'Algorithms can inadvertently amplify sensational and divisive content.',
      'Erodes trust in institutions like journalism, science, and government.',
    ],
    image: 'https://picsum.photos/id/1058/1200/800',
    layout: 'text-left',
    presenter: 2,
  },
  { // 17
    title: 'Privacy in the Digital Age',
    subtitle: 'Your Data is the Product',
    points: [
      'Extensive data collection is the business model for most free platforms.',
      'High-profile scandals (e.g., Cambridge Analytica) have raised public awareness.',
      'Ongoing debate about data ownership, consent, and the need for regulation.',
    ],
    image: 'https://picsum.photos/id/99/1200/800',
    layout: 'text-right',
    presenter: 2,
  },
  { // 18
    title: 'Impact on Politics & Democracy',
    subtitle: 'A Double-Edged Sword for Civic Discourse',
    points: [
      'Politicians can now communicate directly with citizens, bypassing traditional media.',
      'Micro-targeting allows for highly specific political advertising.',
      'Raises concerns about foreign interference, polarization, and the health of public debate.',
    ],
    image: 'https://picsum.photos/id/1029/1200/800',
    layout: 'text-left',
    presenter: 2,
  },
  { // 19
    title: 'Case Study: The Rise of TikTok',
    subtitle: 'How Algorithms Redefined Content Discovery',
    points: [
      'Shifted from a social graph (who you follow) to a content graph (what you like).',
      'Propelled short-form video to become the dominant content format.',
      'Demonstrated the power of AI in creating highly addictive and personalized feeds.',
    ],
    image: 'https://picsum.photos/id/1011/1200/800',
    layout: 'text-right',
    presenter: 2,
  },
  { // 20
    title: 'The Algorithm Effect',
    subtitle: 'Curated Realities and Filter Bubbles',
    points: [
      'Personalized feeds can reinforce existing beliefs, creating echo chambers.',
      'This "filter bubble" can limit exposure to diverse perspectives.',
      'Understanding how algorithms work is crucial for media literacy.',
    ],
    image: 'https://picsum.photos/id/119/1200/800',
    layout: 'text-left',
    presenter: 2,
  },
  // --- Presenter 3: The Future of Social Media (Slides 21-30) ---
  { // 21
    title: 'The Next Frontier: Generative AI',
    subtitle: 'AI as a Co-Creator and Companion',
    points: [
      'AI will create hyper-personalized content, from text to images and video.',
      'Intelligent chatbots and virtual companions will become integrated social features.',
      'Automated content moderation and creation tools will become more sophisticated.',
    ],
    image: 'https://picsum.photos/id/160/1200/800',
    layout: 'text-right',
    presenter: 3,
  },
  { // 22
    title: 'Immersive Social: The Metaverse',
    subtitle: 'Moving Beyond the 2D Screen',
    points: [
      'The concept of persistent, shared 3D virtual spaces for work, play, and socializing.',
      'VR and AR will overlay digital information and experiences onto the physical world.',
      'Represents a fundamental shift from feeds to embodied virtual presence.',
    ],
    image: 'https://picsum.photos/id/177/1200/800',
    layout: 'text-left',
    presenter: 3,
  },
  { // 23
    title: 'The Decentralization Trend',
    subtitle: 'Web3, Blockchain, and User-Owned Data',
    points: [
      'A move away from centralized platforms controlled by single corporations.',
      'Protocols like ActivityPub (Mastodon) create interoperable "fediverses".',
      'The goal is to give users more control over their data, identity, and algorithms.',
    ],
    image: 'https://picsum.photos/id/292/1200/800',
    layout: 'text-right',
    presenter: 3,
  },
  { // 24
    title: 'The Evolution of Content Formats',
    subtitle: 'Ephemeral, Audio, and Interactive',
    points: [
      'Ephemeral content (Stories, Reels) continues to grow, emphasizing authenticity.',
      'Social audio (Clubhouse, Twitter Spaces) offers a more passive, conversational experience.',
      'Live streaming and interactive features will make content more engaging.',
    ],
    image: 'https://picsum.photos/id/326/1200/800',
    layout: 'text-left',
    presenter: 3,
  },
  { // 25
    title: 'Challenge: Combating Deepfakes',
    subtitle: 'The Future of Trust and Authenticity',
    points: [
      'AI-generated synthetic media (deepfakes) will become indistinguishable from reality.',
      'This poses a massive threat for misinformation, fraud, and personal security.',
      'Developing tools for detection and verification will be a critical arms race.',
    ],
    image: 'https://picsum.photos/id/431/1200/800',
    layout: 'text-right',
    presenter: 3,
  },
  { // 26
    title: 'Challenge: Regulation & Responsibility',
    subtitle: 'Balancing Innovation and Safety',
    points: [
      'Governments worldwide are grappling with how to regulate social platforms.',
      'Key issues include data privacy (like GDPR), content moderation, and anti-trust.',
      'Platforms face increasing pressure to be transparent about their algorithms and policies.',
    ],
    image: 'https://picsum.photos/id/514/1200/800',
    layout: 'text-left',
    presenter: 3,
  },
  { // 27
    title: 'Opportunity: Hyper-Niche Communities',
    subtitle: 'Beyond the Megaplatforms',
    points: [
      'Users are seeking smaller, more focused communities centered on specific interests.',
      'Platforms like Discord and Geneva are thriving by offering more intimate spaces.',
      'The future may be less about a single town square and more about many cozy clubhouses.',
    ],
    image: 'https://picsum.photos/id/659/1200/800',
    layout: 'text-right',
    presenter: 3,
  },
  { // 28
    title: 'Opportunity: Social Commerce',
    subtitle: 'The Seamless Integration of Shopping',
    points: [
      'The line between social media and e-commerce is blurring.',
      'Features like in-app checkout, live shopping events, and AR try-ons are becoming common.',
      'Influencers and creators will play an even larger role in driving purchasing decisions.',
    ],
    image: 'https://picsum.photos/id/678/1200/800',
    layout: 'text-left',
    presenter: 3,
  },
  { // 29
    title: 'Our Digital Future is Our Choice',
    subtitle: 'Technology is a tool. The culture we build with it is up to us.',
    points: [
      'The path forward requires proactive engagement from users, not just passive consumption.',
      'We must champion digital literacy, demand transparency, and advocate for platforms that prioritize human values.',
      'Let\'s build a more informed, empathetic, and genuinely connected digital world, together.',
    ],
    image: 'https://picsum.photos/id/145/1200/800',
    layout: 'text-only',
    presenter: 3,
  },
  { // 30
    title: 'Thank You & Q&A',
    subtitle: 'Let\'s Discuss the Future of Social Media',
    points: [
      'What questions do you have?',
      'What do you think is the most significant change coming?',
      'How can we be more mindful social media users?',
    ],
    image: 'https://picsum.photos/id/102/1200/800',
    layout: 'text-only',
    presenter: 3,
  },
];
